// should probs fetch dynamically from a database :)

interface Currency {
  code: string;
  name: string;
  symbol: string | null;
  weight: number | null;
}

interface CurrencySelectOption {
  label: string;
  value: string;
}

export const availableCurrencies: Currency[] = [
  {
    code: "EUR",
    name: "Euro",
    symbol: "€",
    weight: 0,
  },
  {
    code: "USD",
    name: "US Dollar",
    symbol: "$",
    weight: -1,
  },
  {
    code: "GBP",
    name: "Pound Sterling",
    symbol: "£",
    weight: -2,
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    symbol: "$",
    weight: -3,
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    symbol: "$",
    weight: -4,
  },
  {
    code: "AED",
    name: "UAE Dirham",
    symbol: null,
    weight: null,
  },
  {
    code: "AFN",
    name: "Afghani",
    symbol: "؋",
    weight: null,
  },
  {
    code: "ALL",
    name: "Lek",
    symbol: "Lek",
    weight: null,
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    symbol: null,
    weight: null,
  },
  {
    code: "ANG",
    name: "Netherlands Antillian Guilder",
    symbol: "ƒ",
    weight: null,
  },
  {
    code: "AOA",
    name: "Kwanza",
    symbol: null,
    weight: null,
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    symbol: "$",
    weight: null,
  },
  {
    code: "AWG",
    name: "Aruban florin",
    symbol: "ƒ",
    weight: null,
  },
  {
    code: "AZN",
    name: "Azerbaijanian Manat",
    symbol: "ман",
    weight: null,
  },
  {
    code: "BAM",
    name: "Convertible Marks",
    symbol: "KM",
    weight: null,
  },
  {
    code: "BBD",
    name: "Barbados Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "BDT",
    name: "Taka",
    symbol: null,
    weight: null,
  },
  {
    code: "BGN",
    name: "Bulgarian Lev",
    symbol: "лв",
    weight: null,
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    symbol: null,
    weight: null,
  },
  {
    code: "BIF",
    name: "Burundi Franc",
    symbol: null,
    weight: null,
  },
  {
    code: "BMD",
    name: "Bermudian Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "BND",
    name: "Brunei Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "BOB",
    name: "Boliviano",
    symbol: null,
    weight: null,
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    symbol: "R$",
    weight: null,
  },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "BTN",
    name: "Bhutanese ngultrum",
    symbol: "Nu.",
    weight: null,
  },
  {
    code: "BWP",
    name: "Pula",
    symbol: "P",
    weight: null,
  },
  {
    code: "BYN",
    name: "Belarusian Rouble",
    symbol: "Br",
    weight: null,
  },
  {
    code: "BYR",
    name: "Belarussian Ruble",
    symbol: "p.",
    weight: null,
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    symbol: "BZ$",
    weight: null,
  },
  {
    code: "CDF",
    name: "Congolese Franc",
    symbol: null,
    weight: null,
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    weight: null,
  },
  {
    code: "CLF",
    name: "Unidad de Fomento",
    symbol: "UF",
    weight: null,
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    symbol: null,
    weight: null,
  },
  {
    code: "CNY",
    name: "Yuan Renminbi",
    symbol: "¥",
    weight: null,
  },
  {
    code: "COP",
    name: "Peso",
    symbol: null,
    weight: null,
  },
  {
    code: "CRC",
    name: "Costa Rican Colon",
    symbol: "₡",
    weight: null,
  },
  {
    code: "CUC",
    name: "Cuban convertible peso",
    symbol: "$",
    weight: null,
  },
  {
    code: "CUP",
    name: "Cuban Peso",
    symbol: null,
    weight: null,
  },
  {
    code: "CVE",
    name: "Cape Verde Escudo",
    symbol: null,
    weight: null,
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    weight: null,
  },
  {
    code: "DJF",
    name: "Djibouti Franc",
    symbol: null,
    weight: null,
  },
  {
    code: "DKK",
    name: "Danish Krone",
    symbol: "kr",
    weight: null,
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    symbol: "RD$",
    weight: null,
  },
  {
    code: "DZD",
    name: "Algerian Dinar",
    symbol: null,
    weight: null,
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    symbol: "£",
    weight: null,
  },
  {
    code: "ERN",
    name: "Eritrean nakfa",
    symbol: "Nfk",
    weight: null,
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    symbol: null,
    weight: null,
  },
  {
    code: "FJD",
    name: "Fiji Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "FKP",
    name: "Falkland Islands Pound",
    symbol: "£",
    weight: null,
  },
  {
    code: "GEL",
    name: "Lari",
    symbol: null,
    weight: null,
  },
  {
    code: "GGP",
    name: "Guernsey pound",
    symbol: null,
    weight: null,
  },
  {
    code: "GHS",
    name: "Cedi",
    symbol: null,
    weight: null,
  },
  {
    code: "GIP",
    name: "Gibraltar Pound",
    symbol: "£",
    weight: null,
  },
  {
    code: "GMD",
    name: "Dalasi",
    symbol: null,
    weight: null,
  },
  {
    code: "GNF",
    name: "Guinea Franc",
    symbol: null,
    weight: null,
  },
  {
    code: "GTQ",
    name: "Quetzal",
    symbol: "Q",
    weight: null,
  },
  {
    code: "GYD",
    name: "Guyana Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "HNL",
    name: "Lempira",
    symbol: "L",
    weight: null,
  },
  {
    code: "HRK",
    name: "Croatian Kuna",
    symbol: "kn",
    weight: null,
  },
  {
    code: "HTG",
    name: "Gourde",
    symbol: null,
    weight: null,
  },
  {
    code: "HUF",
    name: "Forint",
    symbol: "Ft",
    weight: null,
  },
  {
    code: "IDR",
    name: "Rupiah",
    symbol: "Rp",
    weight: null,
  },
  {
    code: "ILS",
    name: "New Israeli Sheqel",
    symbol: "₪",
    weight: null,
  },
  {
    code: "IMP",
    name: "Isle of Man Pound",
    symbol: "£",
    weight: null,
  },
  {
    code: "INR",
    name: "Indian Rupee",
    symbol: null,
    weight: null,
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    symbol: null,
    weight: null,
  },
  {
    code: "IRR",
    name: "Iranian Rial",
    symbol: "﷼",
    weight: null,
  },
  {
    code: "ISK",
    name: "Iceland Krona",
    symbol: "kr",
    weight: null,
  },
  {
    code: "JEP",
    name: "Jersey pound",
    symbol: "£",
    weight: null,
  },
  {
    code: "JMD",
    name: "Jamaican Dollar",
    symbol: "J$",
    weight: null,
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    symbol: null,
    weight: null,
  },
  {
    code: "JPY",
    name: "Yen",
    symbol: "¥",
    weight: null,
  },
  {
    code: "KES",
    name: "Kenyan Shilling",
    symbol: null,
    weight: null,
  },
  {
    code: "KGS",
    name: "Som",
    symbol: "лв",
    weight: null,
  },
  {
    code: "KHR",
    name: "Riel",
    symbol: "៛",
    weight: null,
  },
  {
    code: "KMF",
    name: "Comoro Franc",
    symbol: null,
    weight: null,
  },
  {
    code: "KPW",
    name: "North Korean Won",
    symbol: "₩",
    weight: null,
  },
  {
    code: "KRW",
    name: "Won",
    symbol: "₩",
    weight: null,
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    symbol: null,
    weight: null,
  },
  {
    code: "KYD",
    name: "Cayman Islands Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "KZT",
    name: "Tenge",
    symbol: "лв",
    weight: null,
  },
  {
    code: "LAK",
    name: "Kip",
    symbol: "₭",
    weight: null,
  },
  {
    code: "LBP",
    name: "Lebanese Pound",
    symbol: "£",
    weight: null,
  },
  {
    code: "LKR",
    name: "Sri Lanka Rupee",
    symbol: "₨",
    weight: null,
  },
  {
    code: "LRD",
    name: "Liberian Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "LSL",
    name: "Loti",
    symbol: null,
    weight: null,
  },
  {
    code: "LTL",
    name: "Lithuanian Litas",
    symbol: "Lt",
    weight: null,
  },
  {
    code: "LVL",
    name: "Latvian Lats",
    symbol: "Ls",
    weight: null,
  },
  {
    code: "LYD",
    name: "Libyan Dinar",
    symbol: null,
    weight: null,
  },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    symbol: null,
    weight: null,
  },
  {
    code: "MDL",
    name: "Moldovan Leu",
    symbol: null,
    weight: null,
  },
  {
    code: "MGA",
    name: "Malagasy Ariary",
    symbol: null,
    weight: null,
  },
  {
    code: "MKD",
    name: "Denar",
    symbol: "ден",
    weight: null,
  },
  {
    code: "MMK",
    name: "Kyat",
    symbol: null,
    weight: null,
  },
  {
    code: "MNT",
    name: "Tugrik",
    symbol: "₮",
    weight: null,
  },
  {
    code: "MOP",
    name: "Pataca",
    symbol: null,
    weight: null,
  },
  {
    code: "MRO",
    name: "Ouguiya",
    symbol: null,
    weight: null,
  },
  {
    code: "MUR",
    name: "Mauritius Rupee",
    symbol: "₨",
    weight: null,
  },
  {
    code: "MVR",
    name: "Rufiyaa",
    symbol: null,
    weight: null,
  },
  {
    code: "MWK",
    name: "Kwacha",
    symbol: null,
    weight: null,
  },
  {
    code: "MXN",
    name: "Peso",
    symbol: null,
    weight: null,
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    weight: null,
  },
  {
    code: "MZN",
    name: "Metical",
    symbol: "MT",
    weight: null,
  },
  {
    code: "NAD",
    name: "Dollar",
    symbol: null,
    weight: null,
  },
  {
    code: "NGN",
    name: "Naira",
    symbol: "₦",
    weight: null,
  },
  {
    code: "NIO",
    name: "Cordoba Oro",
    symbol: "C$",
    weight: null,
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    symbol: "kr",
    weight: null,
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    symbol: "₨",
    weight: null,
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "OMR",
    name: "Rial Omani",
    symbol: "﷼",
    weight: null,
  },
  {
    code: "PAB",
    name: "Balboa",
    symbol: null,
    weight: null,
  },
  {
    code: "PEN",
    name: "Nuevo Sol",
    symbol: "S/.",
    weight: null,
  },
  {
    code: "PGK",
    name: "Kina",
    symbol: null,
    weight: null,
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    symbol: "Php",
    weight: null,
  },
  {
    code: "PKR",
    name: "Pakistan Rupee",
    symbol: "₨",
    weight: null,
  },
  {
    code: "PLN",
    name: "Zloty",
    symbol: "zł",
    weight: null,
  },
  {
    code: "PYG",
    name: "Guarani",
    symbol: "Gs",
    weight: null,
  },
  {
    code: "QAR",
    name: "Qatari Rial",
    symbol: "﷼",
    weight: null,
  },
  {
    code: "RON",
    name: "New Leu",
    symbol: "lei",
    weight: null,
  },
  {
    code: "RSD",
    name: "Serbian Dinar",
    symbol: "Дин.",
    weight: null,
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    symbol: "руб",
    weight: null,
  },
  {
    code: "RWF",
    name: "Rwanda Franc",
    symbol: null,
    weight: null,
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    symbol: "﷼",
    weight: null,
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "SCR",
    name: "Seychelles Rupee",
    symbol: "₨",
    weight: null,
  },
  {
    code: "SDG",
    name: "Sudanese Pound",
    symbol: null,
    weight: null,
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    symbol: "kr",
    weight: null,
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "SHP",
    name: "St Helena Pound",
    symbol: "£",
    weight: null,
  },
  {
    code: "SLL",
    name: "Leone",
    symbol: null,
    weight: null,
  },
  {
    code: "SOS",
    name: "Somali Shilling",
    symbol: "S",
    weight: null,
  },
  {
    code: "SRD",
    name: "Surinam Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "STD",
    name: "Dobra",
    symbol: null,
    weight: null,
  },
  {
    code: "SVC",
    name: "Salvadoran Colon",
    symbol: null,
    weight: null,
  },
  {
    code: "SYP",
    name: "Syrian Pound",
    symbol: "£",
    weight: null,
  },
  {
    code: "SZL",
    name: "Lilangeni",
    symbol: null,
    weight: null,
  },
  {
    code: "THB",
    name: "Baht",
    symbol: "฿",
    weight: null,
  },
  {
    code: "TJS",
    name: "Somoni",
    symbol: null,
    weight: null,
  },
  {
    code: "TMT",
    name: "Manat",
    symbol: null,
    weight: null,
  },
  {
    code: "TND",
    name: "Tunisian Dinar",
    symbol: null,
    weight: null,
  },
  {
    code: "TOP",
    name: "Pa'anga",
    symbol: null,
    weight: null,
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    symbol: "TL",
    weight: null,
  },
  {
    code: "TTD",
    name: "Trinidad and Tobago Dollar",
    symbol: "TT$",
    weight: null,
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    symbol: "NT$",
    weight: null,
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    symbol: null,
    weight: null,
  },
  {
    code: "UAH",
    name: "Hryvnia",
    symbol: "₴",
    weight: null,
  },
  {
    code: "UGX",
    name: "Uganda Shilling",
    symbol: null,
    weight: null,
  },
  {
    code: "UYU",
    name: "Peso",
    symbol: null,
    weight: null,
  },
  {
    code: "UZS",
    name: "Uzbekistan Sum",
    symbol: "лв",
    weight: null,
  },
  {
    code: "VEF",
    name: "Bolivar Fuerte",
    symbol: "Bs",
    weight: null,
  },
  {
    code: "VND",
    name: "Dong",
    symbol: "₫",
    weight: null,
  },
  {
    code: "VUV",
    name: "Vatu",
    symbol: null,
    weight: null,
  },
  {
    code: "WST",
    name: "Samoan tālā",
    symbol: "SAT",
    weight: null,
  },
  {
    code: "XAF",
    name: "CFA Franc BEAC",
    symbol: null,
    weight: null,
  },
  {
    code: "XCD",
    name: "East Caribbean Dollar",
    symbol: "$",
    weight: null,
  },
  {
    code: "XOF",
    name: "CFA Franc BCEAO",
    symbol: null,
    weight: null,
  },
  {
    code: "XPF",
    name: "CFP Franc",
    symbol: null,
    weight: null,
  },
  {
    code: "YER",
    name: "Yemeni Rial",
    symbol: "﷼",
    weight: null,
  },
  {
    code: "ZAR",
    name: "Rand",
    symbol: "R",
    weight: null,
  },
  {
    code: "ZMK",
    name: "Zambian Kwacha",
    symbol: null,
    weight: null,
  },
  {
    code: "ZMW",
    name: "Zambian kwacha",
    symbol: "ZK",
    weight: null,
  },
  {
    code: "ZWL",
    name: "Zimbabwean dollar",
    symbol: "$",
    weight: null,
  },
];

export function getCurrenciesForSelect(): CurrencySelectOption[] {
  return availableCurrencies.map((currency) => ({
    label: `${currency.code} - ${currency.name}`,
    value: currency.code,
  }));
}

export function getCurrencyByCode(code: string): Currency | undefined {
  return availableCurrencies.find((currency) => currency.code === code);
}

export default availableCurrencies;
